apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-apps
  namespace: cozy-public
spec:
  force: false
  interval: 10m0s
  path: ./system
  prune: true
  sourceRef:
    kind: GitRepository
    name: external-apps
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cozystackresourcedefinitions
  namespace: cozy-public
spec:
  force: false
  interval: 10m0s
  path: ./core/cozystackresourcedefinitions
  prune: true
  sourceRef:
    kind: GitRepository
    name: external-apps
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: marketplacepanels
  namespace: cozy-public
spec:
  force: false
  interval: 10m0s
  path: ./core/marketplacepanels
  prune: true
  sourceRef:
    kind: GitRepository
    name: external-apps
